# Generated by Django 4.1.7 on 2023-03-08 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BuildSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BuildPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('length', models.FloatField()),
                ('quantity', models.PositiveIntegerField()),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='RevoHome.build')),
            ],
        ),
        migrations.AddField(
            model_name='build',
            name='build_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RevoHome.buildsection'),
        ),
    ]
