# Generated by Django 4.1.7 on 2023-03-08 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RevoHome', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buildpart',
            name='name',
        ),
    ]
