# Generated by Django 4.1.7 on 2023-03-08 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RevoHome', '0002_remove_buildpart_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='build',
            name='name',
        ),
        migrations.AddField(
            model_name='buildpart',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
