# Generated by Django 4.1.7 on 2023-03-08 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RevoHome', '0003_remove_build_name_buildpart_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildpart',
            name='length',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
